### ISSUE TITLE
Can't get 'libftdi' recipe

### ISSUE THREAD

**Issue by zamashal** [RAKWireless/RAK833-LoRaGateway-SolidRun-Yocto#1]
Getting the following error after running the bitbake command:

> yocto@yocto-VirtualBox:~/poky/build$   nice bitbake core-image-base
WARNING: Host distribution "Ubuntu-16.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Parsing recipes: 100% |#########################################| Time: 00:00:28
Parsing of 948 .bb files complete (0 cached, 948 parsed). 1360 targets, 59 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
**ERROR: Nothing RPROVIDES 'libftdi' (but /home/yocto/poky/meta/recipes-core/images/core-image-base.bb RDEPENDS on or otherwise requires it)**
NOTE: Runtime target 'libftdi' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libftdi']
**ERROR: Required build target 'core-image-base' has no buildable providers.**
**Missing or unbuildable dependency chain was: ['core-image-base', 'libftdi']**

**Comment by RAKWireless** [comment]
@zamashal 
We have fixed the bug.

**Comment by zamashal** [comment]
Thank you!
